### PR TITLE
psxinterpreter: Merge DIV interpreter fix from upstream. (SonofUgly)

### PR DESCRIPTION
**Pull request by gameblabla**
This merges a fix for the interpreter.

The fix came from PCSX-R upstream (before they went bust) and was written by SonofUgly.
See here :
https://github.com/gameblabla/pcsxr/commit/0e5cb8515ed1fb8c01f77290566557bc1e04cf70

### CODE REVIEW

**Comment by notaz** [comment]
Does this actually fix anything?
The _rRs_ 0x80000000 is already handled for us by host CPUs (at least x86 or ARM), so having that will give slower code with 0 benefit.
The _rHi_ being unmodified case makes no sense and doesn't match mednafen.

**Comment by gameblabla** [comment]
https://github.com/SonofUgly/PCSX-Reloaded/commit/33620557294def7ae109e55027f542a061705053

He tested it against amidog's CPU test apparently (and he claimed to have took it from Mednafen PSX).

I guess i should try amigo's cpu test with it before we can merge this.

**Comment by gameblabla** [comment]
It probably should be reimplemented like this, no ? Does it still make sense ?
(It still doesn't pass the cputest though btw but at least it doesn't crash and looks to be correct)
https://github.com/libretro/pcsx_rearmed/pull/530

**Comment by notaz** [comment]
You can add it for x86 if you like, but it's definitely not needed for ARM (I was curious and checked) so no need to slow it. Enclose with something like
```
#if !defined(__arm__) && !defined(__aarch64__)
...
#endif
```

**Pull request closed without merging**
