### PR TITLE
Icache emulation from PCSX Redux + Senquack changes from PCSX4ALL

### PR DESCRIPTION
**Pull request by gameblabla**
See (Redux) :
https://github.com/grumpycoders/pcsx-redux/commit/1923ce54ef585beba3a948d50f8c30161102312c

See original icache implementation (mirror of PCSX Reloaded):
https://github.com/gameblabla/pcsxr

Without icache emulation, F1 2001 will greatly misbehave :
if you accelerate, the car will go around like crazy.
With icache emulation, it works as intended.

Our code is slightly different from theirs as i found out that having the icache arrays in psxregs would cause crashes.
Instead, i'm taking them out of there and only allocating them on the heap (due to their great size).

I'm open for suggestions. For example, should i put writeok in Psxregs or out of it ?

**EDIT**: I should point out this doesn't add icache emulation for the ARM dynarec. That will need to be done by someone else.

### CODE REVIEW

**Comment by gameblabla** [comment]
I modified it so it no longer conflicts with current master (the interpreter/ARM issue got fixed so yay) but i still put them in a define.
There is a potential blocker for this merge and it's this :
https://github.com/gameblabla/pcsx_rearmed/blob/91466b1783f2e86fa25a05f924d0e5982b5f75b6/libpcsxcore/r3000a.c#L88
```c
	((((psxRegs.code = PSXMu32(psxRegs.pc)) >> 24) & 0xfe) == 0x4a))
	{
		// "hokuto no ken" / "Crash Bandicot 2" ...
		// BIOS does not allow to return to GTE instructions
		// (just skips it, supposedly because it's scheduled already)
		// so we execute it here
		extern void (*psxCP2[64])(void *cp2regs);
		psxCP2[psxRegs.code & 0x3f](&psxRegs.CP2D);
	}
```

This has always existed in PCSX Reloaded and was for a good while in PCSX Redux until it was removed after they merged some psxexceptions fixes.
I removed it just to see if it would back fire in hokuto no ken and it didn't crash... it seems that this piece of code wouldn't work on the ARM dynarec either...
Why does it exist ?

**Comment by gameblabla** [comment]
So turns out the different code isn't really related to their new exception code so i just borrowed it as it was done here :
https://github.com/grumpycoders/pcsx-redux/commit/59ce167d46e44f641d00e9b57b4ac003e052f0ba#diff-3aa36efa444cebab201ee66289d90a5bf8d4a5ca2a3f496283fcac8714093c27R208

And i've done it as such :
https://github.com/notaz/pcsx_rearmed/pull/198/commits/64349c124a6f434a73d3eb25f26215fd1ce0a410

I also noticed there was an extra printf in bd so i also removed it. (i wonder if this caused the slowdowns in some games...)

**Comment by gameblabla** [comment]
Alright, after some changes (and a few mistakes that i corrected), i feel like this should be ready.
It can be forced disabled but even when it is enabled, you can choose to disable it at runtime.
This allows you to (manually) get past the the lockup on Spyro 2 with icache emulation and still be able to play the F1 games that do require icache emulation until the issue is resolved. (PCSX Reloaded and PCSX redux have the same issue with icache)

Among the games now playable, these include at least F1 Arcade and F1 2001.
This should also allow F1 99 to be playable as well.
By default, icache is turned off but can be turned on at any time. Users that want to avoid the overhead and size implications of the icache emulation can choose to disable it.
I have chosen to disable compiling the code on the Pandora, Caanoo, Maemo etc...

**Comment by notaz** [comment]
I think it would help to trim this further, like `mem_bak` changes don't look useful for rearmed, as well as `ari64_notify` should be better be empty than contain wrong code it contains now. If removing `mem_bak` stuff breaks games, commenting out all the `psxMemRLUT` mem*() calls in `psxMemWrite32` should get the same effect without all the mess.

**Comment by gameblabla** [comment]
Hey,
The mem_bak changes are not required for the interpreter but they could be if i end up merging the MIPS dynarec back to PCSX Rearmed. (though i'm waiting on you to merge the threaded renderer before i attempt that)

As "consolation", i decided to also put my other intepreter fixes from PCSX Redux that allows F1 2000 to *sometimes* boot correctly and not freeze.
Note that i didn't merge the delayed reads from PCS Redux so it could be why F1 2000 isn't totally stable.

**Comment by gameblabla** [comment]
I forgot to say it but i took out the mem_back changes too.

**Comment by notaz** [comment]
> The mem_bak changes are not required for the interpreter but they could be if i end up merging the MIPS dynarec back to PCSX Rearmed.

So you want to merge in a whole other dynarec? Ideally ari64's one would just gain support more platforms, but I agree that's really difficult to do...

Anyway this now looks ok to me, merging.

**Pull request merged**
