### PR TITLE
Libretro threaded renderer  + ARM optimized Unai renderer from libretro's fork

### PR DESCRIPTION
**Pull request by gameblabla**
Libretro's fork made some interesting progress and they notably merged a threaded renderer that does make a difference in terms of performance.
It has been tested and works against Unai and Peops (dfxvideo).
On my PC, the threaded renderer at Yugioh's title screen allows me to gain around 13 FPS or so.

However upstream, they disabled it for the neon + GLES backend.
I don't see any reason why this wouldn't work for the GLES backend so i left it as is. (the GLES backend doesn't work on my PC no matter what, even without this PR)
They also didn't explain why this wouldn't work for the NEON backend. (probably that the benefits are not noticeable on ARM platforms ?)
In any case, the threaded renderer is disabled by default and can be enabled with --enable-thread-gpu via ./configure.

There were also a few issues as well upstream.
For example, Peops doesn't compile there due to a mistake so i fixed this in my branch. (renderer_notify_update_lace and renderer_sync were copied twice)

Unfortunately some of the authors removed their own branch and there are a lot of commits to worry about.
It seems that they are diverging away from this branch and more focusing on libretro :/
It all works for me but let me know if there is a cleaner way of merging this.

### CODE REVIEW

**Comment by justinweiss** [comment]
Awesome! Happy to see the work put into getting this upstreamed.

There wasn't a _good_ reason the threaded renderer wasn't enabled for neon / gles, just that I didn't have a good way to test neon / gles implementations, and my focus was making it playable on 3DS. I don't think it would take much work to get it working in the other implementations for someone with a good build / test setup.

**Comment by gameblabla** [comment]
Should i disable pixel_skip by default for Unai?
In retroarch, it's set to 1 but it's mostly intended for low resolution platforms where the drawback of skipping every 2nd line won't be as noticeable.
However on high resolutions or stuff that just displays it as is, it will be noticeable and looks ugly.

**Comment by justinweiss** [comment]
It looks like it's turned on in `emu_set_default_config`, and then turned off by the core option default in `libretro_core_options.h`. Same with fast lighting. I don't know why it's inconsistent, but it seems to me like "disabled" is the better default, like you said.

**Comment by gameblabla** [comment]
I'm not seeing any issues so far so unless notaz notices an issue or something he would like me to improve, i consider it done and good for merging.

**Comment by gameblabla** [comment]
I put back the WIP mark as i've noticed that it gets me a black screen on Worms Pinball unlike the original plugins and all.
That game is notorious for having various issues and it seems that compiling PCSX rearmed as 32-bits fix those crashing issues at least. (although they still don't really solve the other issues)

**Comment by gameblabla** [comment]
So another update : I rebased my PR and it turns out i inadvertently fixed Worms Pinball with some of my PRs.
Before that, it would lead to a black screen. Now it goes further. However, the game will still crash after the FMV videos.
This PR + forcing GCC to compile the code as -m32 gets further and makes the game playable.

It's likely it suffers from these issues because PCSX Rearmed's unsigned long are assumed to be 32-bits in size.
Should i also fix those issues in there ?

**Comment by gameblabla** [comment]
I made some further regression testing on Worms Pinball and this commit does not actually affect this game.
My CDROM timings changes were the one responsible for fixing up the game :
https://github.com/notaz/pcsx_rearmed/commit/dc0ee8d424293ea687a137ec1ca0440f88a1e5a5

I also resolved the conflicts this had with the master branch and removed the in_type changes as these, even though they came from upstream, are quite unnecesarry. Maybe i'll do a clean-up PR later.

In any case for these reasons, i removed the WIP mark again on it, it should be good now.

**Comment by notaz** [comment]
And doesn't even compile on pandora:
```
make[1]: Entering directory '/home/notaz/dev/arm/pcsxr-1.9.92/plugins/dfxvideo'
arm-unknown-linux-gnueabi-gcc -o gpu_peops.so -Wall -ggdb -O2 -fno-strict-aliasing -ffast-math -I../../include -mcpu=cortex-a8 -mtune=cortex-a8 -mfpu=neon -DRAM_FIXED -D_FILE_OFFSET_BITS=64 -Wno-unused-result -fPIC  -shared -Wl,--no-undefined gpulib_if.c ../gpulib/gpulib.a  
/tmp/tmp//ccgqTJ5l.o: In function `renderer_init':
/home/notaz/dev/arm/pcsxr-1.9.92/plugins/dfxvideo/gpulib_if.c:316: undefined reference to `gpu'
/tmp/tmp//ccgqTJ5l.o: In function `do_cmd_list':
/home/notaz/dev/arm/pcsxr-1.9.92/plugins/dfxvideo/gpulib_if.c:334: undefined reference to `cmd_lengths'
/home/notaz/dev/arm/pcsxr-1.9.92/plugins/dfxvideo/gpulib_if.c:334: undefined reference to `gpu'
/tmp/tmp//ccgqTJ5l.o: In function `set_vram':
/home/notaz/dev/arm/pcsxr-1.9.92/plugins/dfxvideo/gpulib_if.c:294: undefined reference to `gpu'
collect2: error: ld returned 1 exit status
```

**Comment by notaz** [comment]
One solution would be to have both old and new unai as separate plugins, since the code has changed so much it could be seen as a new thing. Could be named gpu_senquack or something. Or just rename the old one to unai_old for things to not differ from other forks too much.
As for the threading I don't have anything against it, if it was separate I'd be happy to merge it.

**Comment by gameblabla** [comment]
https://github.com/notaz/pcsx_rearmed/pull/233
Based on your feedback, i have opened that separates the Unai changes in another plugin.
For now, let's not merge this until i rework it for that PR later when it does get merged.

**Comment by gameblabla** [comment]
Does pcsx_rearmed still lack the threaded renderer ? i admit, it's a been a while since i looked at this...

**Comment by notaz** [comment]
This repo still does. But from what I saw the libretro fork has it enabled only for the 3DS, and that has some random crash reports (3DS only) that I strongly suspect is threaded rendering related. I really dislike such instability.

**Comment by justinweiss** [comment]
I haven't worked on this in a very long time, but I remember enabling it only for 3DS because it was the only device I had access to that was multicore, but also slow and didn't support neon. It doesn't seem like a common combination.

I heard about crashes on old 3DS. Those seemed to be caused by the limited number of threads it would allow you to spawn, and would either crash or lose functionality depending on which order the libretro and pcsx_rearmed threads were started in. Old 3DS only supported running user threads on one core IIRC, so it'd probably be slower even if it could work. I haven't heard about crashes tied to the threaded renderer on New 3DS, at least that I've seen or have been reported to me, but again I haven't participated in a while.

On New 3DS, it seemed to make a big difference for games that didn't need to sync CPU to GPU on every frame. But I'm not sure how many other slow multicore non-neon devices are out there, and that's the only place I'd expect to see a difference.

**Comment by gameblabla** [comment]
Well even if i were to fix this, i personally dislike having two separate unai drivers just for the multithreaded renderer...
Surely there is a better way ?

**Comment by notaz** [comment]
It could be generalized to work with any gpu plugin, but that means effort now and extra maintenance burden for future. I think I prefer this situation to stay as-is (keep it in libretro fork enabled for N3DS only).

**Comment by gameblabla** [comment]
Let's just close this for now, someone else (or myself) will redo it anyway.

**Pull request closed without merging**
